server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: candidate-service
        uri: lb://candidate-service
        predicates:
        - Path=/home/candidate/**